[options]
admin_passwd = NMN#Pc4=m6yP^-E
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password
proxy_mode = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
